server:
  servlet:
    context-path: "/api/1.0/"

spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?zeroDateTimeBehavior=convertToNull"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
